"use strict";

import Media from "./Media";

import {
    ContainerType,
    HdrType,
    HlsSegmentFormat,
    HlsVideoSegmentFormat,
    IdleReason,
    MediaCommand,
    MetadataType,
    PlayerState,
    QueueType,
    RepeatMode,
    ResumeState,
    StreamType,
    TextTrackEdgeType,
    TextTrackFontGenericFamily,
    TextTrackFontStyle,
    TextTrackType,
    TextTrackWindowType,
    TrackType,
    UserAction
} from "./enums";

import {
    AudiobookChapterMediaMetadata,
    AudiobookContainerMetadata,
    Break,
    BreakClip,
    BreakStatus,
    ContainerMetadata,
    EditTracksInfoRequest,
    GenericMediaMetadata,
    GetStatusRequest,
    LiveSeekableRange,
    LoadRequest,
    MediaInfo,
    MediaMetadata,
    MovieMediaMetadata,
    MusicTrackMediaMetadata,
    PauseRequest,
    PhotoMediaMetadata,
    PlayRequest,
    QueueData,
    QueueInsertItemsRequest,
    QueueItem,
    QueueJumpRequest,
    QueueLoadRequest,
    QueueRemoveItemsRequest,
    QueueReorderItemsRequest,
    QueueSetPropertiesRequest,
    QueueUpdateItemsRequest,
    SeekRequest,
    StopRequest,
    TextTrackStyle,
    Track,
    TvShowMediaMetadata,
    UserActionState,
    VastAdsRequest,
    VideoInformation,
    VolumeRequest
} from "./classes";

export default {
    DEFAULT_MEDIA_RECEIVER_APP_ID: "CC1AD845",
    timeout: {
        editTracksInfo: 0,
        getStatus: 0,
        load: 0,
        pause: 0,
        play: 0,
        queue: 0,
        seek: 0,
        setVolume: 0,
        stop: 0
    },

    Media,

    // Enums
    ContainerType,
    HdrType,
    HlsSegmentFormat,
    HlsVideoSegmentFormat,
    IdleReason,
    MediaCommand,
    MetadataType,
    PlayerState,
    QueueType,
    RepeatMode,
    ResumeState,
    StreamType,
    TextTrackEdgeType,
    TextTrackFontGenericFamily,
    TextTrackFontStyle,
    TextTrackType,
    TextTrackWindowType,
    TrackType,
    UserAction,

    // Classes
    AudiobookChapterMediaMetadata,
    AudiobookContainerMetadata,
    Break,
    BreakClip,
    BreakStatus,
    ContainerMetadata,
    EditTracksInfoRequest,
    GenericMediaMetadata,
    GetStatusRequest,
    LiveSeekableRange,
    LoadRequest,
    MediaInfo,
    MediaMetadata,
    MovieMediaMetadata,
    MusicTrackMediaMetadata,
    PauseRequest,
    PhotoMediaMetadata,
    PlayRequest,
    QueueData,
    QueueInsertItemsRequest,
    QueueItem,
    QueueJumpRequest,
    QueueLoadRequest,
    QueueRemoveItemsRequest,
    QueueReorderItemsRequest,
    QueueSetPropertiesRequest,
    QueueUpdateItemsRequest,
    SeekRequest,
    StopRequest,
    TextTrackStyle,
    Track,
    TvShowMediaMetadata,
    UserActionState,
    VastAdsRequest,
    VideoInformation,
    VolumeRequest
};
